@startuml
Class Client {
}

Class Proxy {
}

Class TransactionWorker {
}

Class TransactionManager {
}

Class Server {

}

Class AccountManager {

}

Class Account {
    
}



Server "1" -- "1" TransactionManager
Server "1" -- "1" AccountManager

Proxy "1" -- Client
Proxy "1" -- "1" TransactionWorker
TransactionManager "1" -- "many" TransactionWorker
AccountManager "1" -- "many" Account

@enduml